### PR TITLE
Update to thorntail.io (#49)

### PR DESCRIPTION
**Pull request by cchet**
Migrated to thorntail.io and updated other dependencies like hammock and arquillian-universe.
When merged, then profile **wildfly-swarm** should be named **thorntail-io**, as well as travis builds need to be modified to use the new profile name.

Excluded *.iml file from maven-rat-plugin, because caused build to fail locally, because there was no license header present.

Modified test classes of the swagger sample, where deltaspike is now used to exclude classes, which shouldn't be present when thorntail.io is used, because thorntail.io already provides a swagger integration.

Signed-off-by: Thomas Herzog <herzog.thomas81@gmail.com>

### CODE REVIEW

**Comment by cchet** [comment]
The test of job #55.2 passed, but throw the following error, which also occurred locally. Any ideas why ?

> java.io.StreamCorruptedException: invalid stream header: 48545450

**Comment by cchet** [comment]
Any feedback ?

**Comment by kenfinnigan** [comment]
I've taken a brief look through and I think a problem I've seen is that there are lots of changes completely unrelated to switching to use Thorntail from WildFly Swarm.

It might be a pain, but it's easier to know what's exactly needed if we split this into several separate PRs

**Comment by cchet** [comment]
Ok, no problem. I split the changes up

**Pull request closed without merging**
