### PR TITLE
Fixes #11

### LINKED ISSUE #11: Fails to build without profile
Currently running `mvn clean install` fails as there is no Arquillian container present for the test to run.

Would be nice if we could build the project without having to run the test

### PR DESCRIPTION
**Pull request by kenfinnigan**
Adds a profile thats active by default that skips all surefire tests

### CODE REVIEW

**Comment by karianna** [comment]
Hmmm, do we really want the default to skip tests?

**Comment by kenfinnigan** [comment]
My thoughts behind this is that we're no longer running a profile, such as WildFly, as default which means the test fails and the build breaks.

Given that, I thought it was preferable that the skinny WAR of the applications could be built at a minimum with the basic `mvn clean package`.

If everyone's ok with the build failing without a profile for testing being set, then that's fine

**Comment by karianna** [comment]
I'd rather run the tests as the default.  I assume the issue there is that we 'favour' one vendor over another?

**Comment by kenfinnigan** [comment]
Right.

Previously it was using WildFly by default but that was removed.

**Comment by karianna** [comment]
I'm hoping this: https://groups.google.com/forum/#!topic/microprofile/UmSBaVD_ZLk will resolve the issue long term.  In the meantime I guess it's better to have running out of the box.

**Pull request merged**
