### PR TITLE
Feature/thorntail-config-sample

### PR DESCRIPTION
**Pull request by cchet**
This branch is based on feature/thorntail of PR #50 and adds a microprofile-sample-config project for microprofile-config usage.

See README for available endpoints and expected configuration parameters.

I have still some little issues:
- Needed to use JAXRSArchive for thorntail tests, which is provided by thorntail, because with WEBArchive, fraction detection did not find the dependency to microprofile-config

### CODE REVIEW

**Comment by cchet** [comment]
So, now I consider it done. Added additional test methods

**Comment by cchet** [comment]
Any feedback ?

**Comment by kenfinnigan** [comment]
I think it would be easier for #50 to be merged and included before considering what this PR is looking to bring.

Separate to that, are there any reasons to have a separate example rather than add Config usage into the main example?

**Comment by cchet** [comment]
I thought a sample project per microprofile specification is intended. There is no problem to merge the config sample with the main sample

**Comment by kenfinnigan** [comment]
Honestly I can't recall what the original intent of that repo was, other than a way to show an app running on all the containers

**Comment by cchet** [comment]
Is the repository considered to stay alive ? 
I thought the repository is for showing samples, how to use the different microprofile specifications in a microservice, or in particular a standalone application.

**Comment by kenfinnigan** [comment]
The activeness of this repository and microprofile-conference is something to be discussed in the community.

I'm not sure if the samples repo was intended to showcase every spec in a different module, as opposed to just adding to the main canonical one

**Comment by cchet** [comment]
Ok , but is worth to invest further work on this PR and PR #50, if its just showing an app running on multiple containers ?

**Comment by kenfinnigan** [comment]
Sorry for the delayed response @cchet 

I'm going to be posting to the Forum soon explain some thoughts around this that may make this PR alter a bit in it's focus

**Comment by cchet** [comment]
No problem. Thanks for the response

**Pull request closed without merging**
